### ISSUE TITLE
Unable to Deposit Into Aave

### ISSUE THREAD

**Issue by dhamoui** [PatrickAlphaC/aave_web3_py#1]
Hello,

I'm trying to follow your example. I am attempting to run aave_borrow_web3.py, but the function is failing when it reaches the deposit function. I get the following error:

```
Approving ERC20...
Approved 90000000000000000 tokens for contract 0xE0fBa4Fc209b4948668006B2bE61711b7f465bAe
Depositing to Aave...
Traceback (most recent call last):
  File "/home/ec2-user/environment/aave_protocol.py", line 211, in <module>
    main()
  File "/home/ec2-user/environment/aave_protocol.py", line 33, in main
    tx_hash = deposit_to_aave(w3, amount, lending_pool, nonce=nonce_two)
  File "/home/ec2-user/environment/aave_protocol.py", line 148, in deposit_to_aave
    "nonce": nonce,
  File "/home/ec2-user/.local/lib/python3.7/site-packages/web3/contract.py", line 1087, in buildTransaction
    **self.kwargs
  File "/home/ec2-user/.local/lib/python3.7/site-packages/web3/contract.py", line 1648, in build_transaction_for_function
    prepared_transaction = fill_transaction_defaults(web3, prepared_transaction)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/home/ec2-user/.local/lib/python3.7/site-packages/web3/_utils/transactions.py", line 102, in fill_transaction_defaults
    default_val = default_getter(web3, transaction)
  File "/home/ec2-user/.local/lib/python3.7/site-packages/web3/_utils/transactions.py", line 66, in <lambda>
    'gas': lambda web3, tx: web3.eth.estimate_gas(tx),
  File "/home/ec2-user/.local/lib/python3.7/site-packages/web3/eth.py", line 728, in estimate_gas
    return self._estimate_gas(transaction, block_identifier)
  File "/home/ec2-user/.local/lib/python3.7/site-packages/web3/module.py", line 60, in caller
    null_result_formatters)
  File "/home/ec2-user/.local/lib/python3.7/site-packages/web3/manager.py", line 190, in request_blocking
    null_result_formatters)
  File "/home/ec2-user/.local/lib/python3.7/site-packages/web3/manager.py", line 168, in formatted_response
    raise ValueError(response["error"])
ValueError: {'code': -32016, 'data': 'Reverted', 'message': 'The execution failed due to an exception.'}
```

The only things I have changed from your project to mine are the KOVAN_RPC_URL, my private key, and my_address which I'm now defining as my_address = Web3.toChecksumAddress('0xe6c3e6373Ea83da6A555Fcee944038308130bB67').

And you can see the transactions getting approved here: https://kovan.etherscan.io/address/0xe6c3e6373Ea83da6A555Fcee944038308130bB67

Additionally, [this comment](https://github.com/ethers-io/ethers.js/issues/903#issuecomment-662713803) indicates that error code "-32016" corresponds to "token transfer failed".

This is my first attempt at programming with Web3 and I'm very excited about the defi space so any help here would be greatly appreciated.

Thanks

**Comment by dhamoui** [comment]
Apologies, I had not run the get_weth module. Please disregard this issue.

**Comment by PatrickAlphaC** [comment]
Great work!
